"""Build a local review artifact from real browser captures and human assessments."""
from pathlib import Path
import json,html
root=Path('artifacts/super-polish'); report=json.loads((root/'final/visual-assessment.json').read_text())
entries=[]
for row in report['rows']:
 ident=row['id'];motion=next((phase for phase in ['iteration-7-motion','iteration-6-motion'] if (root/phase/f'motion-{ident}.json').exists()),None)
 high='iteration-7-high' if (root/'iteration-7-high'/f'report-{ident}.json').exists() else 'iteration-6-high'
 frames=sorted((root/motion).glob(f'motion-{ident}-*.png')) if motion else []
 entry={**row,'modelImage':f'../iteration-5-high/model-{ident}.png','baselineImage':f'../baseline/model-{ident}.png','iconImage':f'../iteration-5-high/icon-{ident}.png','frames':[f'../{motion}/{p.name}' for p in frames],'highFrames':[f'../{high}/effect-{ident}-{n}.png' for n in range(4)]}
 entries.append(entry)
payload=json.dumps(entries).replace('</','<\\/')
page='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Super weapon visual review</title>
<style>*{box-sizing:border-box}body{margin:0;background:#101b20;color:#e9eee7;font:15px system-ui;line-height:1.5}main{max-width:1180px;margin:auto;padding:32px}h1{margin-bottom:4px}p{max-width:85ch;color:#bccbc5}a{color:#94ddc3}select,button,input{font:inherit}select,button{padding:9px;background:#21322b;color:inherit;border:1px solid #526a5d}nav{display:flex;gap:10px;margin:25px 0;flex-wrap:wrap}figure{margin:0}figcaption{font:12px monospace;color:#a2b9ad;margin:8px 0}img{display:block;max-width:100%;background:#10211b}.models{display:grid;grid-template-columns:1fr 1fr;gap:20px}.models img{width:100%;height:230px;object-fit:contain}.scores{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.score{font-size:34px}.detail{font-size:13px;color:#bccbc5}.frames{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:28px}.frames img{width:100%}input[type=range]{width:100%}table{border-collapse:collapse;width:100%;margin-top:40px}th,td{padding:9px;border-bottom:1px solid #31453c;text-align:left}tr button{padding:2px 6px;border:0;background:transparent;color:#94ddc3}summary{cursor:pointer}@media(max-width:700px){main{padding:18px}.frames,.models,.scores{grid-template-columns:1fr}.models img{height:190px}}</style>
<main><h1>Super weapon visual review</h1><p>All 27 supers. Five fixed dimensions, each worth 20: identity, craft, hierarchy, presentation and integration. Scores are an art-direction assessment, not a benchmark. Ordinary weapons are outside this review.</p><p><a href="../../../SUPER_POLISH_REVIEW.md">Rubric and revision history</a> · <a href="visual-assessment.json">Detailed assessment</a> · <a href="../iteration-5/icons-optical-sizes.png">22 / 34 / 48 px icon atlas</a></p><nav><button id="prev">← Previous</button><select id="weapon" aria-label="Super weapon"></select><button id="next">Next →</button></nav><div class="scores" id="scores"></div><div class="models"><figure><img id="baseline"><figcaption>Original model</figcaption></figure><figure><img id="model"><figcaption>Revised model · shipping geometry and materials</figcaption></figure></div><div class="frames"><figure><img id="motion"><figcaption id="time"></figcaption><input id="scrub" type="range" min="0" value="0" aria-label="Animation sample"></figure><figure><img id="high"><figcaption>High-quality combat capture</figcaption><input id="stage" type="range" min="0" max="3" value="1" aria-label="High quality stage"></figure></div><details><summary>Individual observations</summary><div id="notes"></div></details><table><thead><tr><th>Super</th><th>Small icon</th><th>3D signature</th><th>Effect</th></tr></thead><tbody id="table"></tbody></table><p>Motion samples use authoritative simulation time at 0.1-second intervals, with selected rendered frames shown here. High-quality captures retain the full game interface. Software rendering was used for review; no hardware frame-rate claim is made.</p></main>
<script>const rows=__DATA__;const $=id=>document.getElementById(id);const score=c=>c&&c.dimensions.every(v=>v!==null)?c.dimensions.reduce((a,b)=>a+b,0):'Pending';rows.forEach((r,i)=>{const o=new Option(r.name||r.id,i);$('weapon').add(o);const tr=document.createElement('tr');tr.innerHTML=`<td><button data-index="${i}">${r.name||r.id}</button></td><td>${score(r.icon)}</td><td>${score(r.model)}</td><td>${score(r.effect)}</td>`;$('table').append(tr)});function frame(){const r=rows[+$('weapon').value],f=r.frames[+$('scrub').value];$('motion').src=f||'';$('time').textContent=f?`Simulation tick ${+f.match(/-(\\d+)\\.png$/)[1]} · full sequence reviewed through expiry`:"Pending";$('high').src=r.highFrames[+$('stage').value]}function show(){const r=rows[+$('weapon').value];$('baseline').src=r.baselineImage;$('baseline').alt=`Original ${r.id} model`;$('model').src=r.modelImage;$('model').alt=`Revised ${r.id} model`;$('scores').innerHTML=['icon','model','effect'].map(k=>`<div><div class="detail">${{icon:'SMALL ICON',model:'3D SIGNATURE',effect:'COMBAT EFFECT'}[k]}</div><div class="score">${score(r[k])}<span class="detail"> / 100</span></div></div>`).join('');$('notes').textContent=['icon','model','effect'].map(k=>`${k}: ${r[k]?.observation||'Review pending.'}`).join(' ');$('scrub').max=Math.max(0,r.frames.length-1);$('scrub').value=Math.min(3,r.frames.length-1);frame()}$('weapon').onchange=show;$('scrub').oninput=frame;$('stage').oninput=frame;$('prev').onclick=()=>{$('weapon').value=(+$('weapon').value+26)%27;show()};$('next').onclick=()=>{$('weapon').value=(+$('weapon').value+1)%27;show()};$('table').onclick=e=>{if(e.target.dataset.index){$('weapon').value=e.target.dataset.index;show();window.scrollTo(0,0)}};show();</script>'''
(root/'final/index.html').write_text(page.replace('__DATA__',payload))
